### ISSUE TITLE
如何取消掉打开右侧边栏功能？

### ISSUE THREAD

**Issue by xuekevin** [oopww1992/WWSideslipViewController#1]
如题？还想咨询一下，类似实现该功能的代码还有那些？ 谢谢！

**Comment by beforeold** [comment]
很少在github上互动，借这里向看到这段话的同学请教下，这个demo的设计模式与一般的view addSubView的设计模式上有很大的区别，而是addSubview:anotherController.view，先谢谢了。

**Comment by hanjunqiang** [comment]
@lcddhr 把右侧的代码去掉，你在MainVC中用手画圆圈就会有bug,你发现了？

**Comment by hanjunqiang** [comment]
Demo中就有啊，你仔细看下

发自我的vivo智能手机

xuekevin <notifications@github.com>编写：
